### ISSUE TITLE
The footer covers the bottom of the venue setup pages

### ISSUE THREAD

**Issue by tjoneslo** [ChicagoWorldcon/planorama#760]
I've gotten the published staging version of planorama running. I'm trying to set up our venue, but can't because the footer covers the "cancel" / "save" buttons at the bottom of the page. So I can't tell which option is selected to create the venue and the other options.

**Comment by Gailbear** [comment]
the quick fix for this is the rake task called chicon.rake, but customize it for yourself. we still need to actually design this page. if you want an example of customizing, take a look at arisia.rake in the arisia branch

**Comment by Gailbear** [comment]
the other thing you can do as a temporary fix is go into the browser inspector and add the class "scrollable" to the container element... I can probably give you a one liner that does this, hold on.

**Comment by Gailbear** [comment]
lolol surprising third option - this is one of those pages that is surprisingly not broken on your phone. I mean it's definitely broken looking, but the buttons appear fine, interestingly. you could probably also zoom out your page an absurd amount as a quick fix.

**Comment by Gailbear** [comment]
Ok workaround: On the venue page, open up your javascript console, and run the following 3 lines:
```javascript
$('.tab-pane .scrollable').classList.remove('scrollable')
$('.b-overlay-wrap.position-relative').classList.remove('position-relative')
$('.b-overlay-wrap').classList.add('scrollable')
```
Then click each of the other 2 tabs (venues and room setups) and run just the first line while on each tab. That should at least make the scrolling work right until we fix it.

**Comment by Gailbear** [comment]
Internal ticket: https://chicon-planorama.atlassian.net/browse/PLAN-805
